CREATE TABLE citas (
    id INT PRIMARY KEY AUTO_INCREMENT,
    fecha VARCHAR(255) NOT NULL,
    hora VARCHAR(255) NOT NULL,
    peluquero INT NOT NULL,
    usuario INT,
    tipo VARCHAR(255) NOT NULL DEFAULT 1,
    pagado BOOLEAN NOT NULL DEFAULT FALSE,
    realizada BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE citas ADD CONSTRAINT tipo FOREIGN KEY (tipo) REFERENCES tipo(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
