CREATE TABLE roles (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(20) NOT NULL,
    nivel INT NOT NULL DEFAULT 0
);

INSERT INTO roles VALUES (0, 'USUARIO', 0);
INSERT INTO roles VALUES (1, 'PELUQUERO', 5);
INSERT INTO roles VALUES (2, 'JEFE-PELUQUERO', 10);
INSERT INTO roles VALUES (3, 'JEFE', 10);